const REQUEST_GET_DATA = 'REQUEST_GET_DATA';
const GET_DATA = 'GET_DATA';
const GET_DATA_BY_ID = 'GET_DATA_BY_ID';
const REQUEST_UPDATE_DATA = 'REQUEST_UPDATE_DATA';
const UPDATE_DATA = 'UPDATE_DATA';
const REQUEST_DELETE_DATA = 'REQUEST_DELETE_DATA';
const DELETE_DATA = 'DELETE_DATA';
const REQUEST_CREATE_DATA = 'REQUEST_CREATE_DATA';
const CREATE_DATA = 'CREATE_DATA';
const GET_DATA_FAILED = 'GET_DATA_FAILED';
const UPDATE_DATA_FAILED = 'UPDATE_DATA_FAILED';
const DELETE_DATA_FAILED = 'DELETE_DATA_FAILED';
const GET_DATA_BY_ID_FAILED = 'GET_DATA_BY_ID_FAILED';
const CREATE_DATA_FAILED = 'CREATE_DATA_FAILED';
const REQUEST_GET_DATA_BY_ID = 'REQUEST_GET_DATA_BY_ID';

export {
  REQUEST_DELETE_DATA,
  REQUEST_GET_DATA,
  REQUEST_UPDATE_DATA,
  GET_DATA,
  GET_DATA_BY_ID,
  UPDATE_DATA,
  DELETE_DATA,
  REQUEST_CREATE_DATA,
  CREATE_DATA,
  CREATE_DATA_FAILED,
  GET_DATA_BY_ID_FAILED,
  GET_DATA_FAILED,
  UPDATE_DATA_FAILED,
  DELETE_DATA_FAILED,
  REQUEST_GET_DATA_BY_ID,
};
